version: "3.8"
services:
  postgresql:
    image: postgres:13
    container_name: rbac_postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rbac
    volumes:
      - ~/data/postgresql/rbac:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: redis:latest
    container_name: rbac_redis
    restart: always
    volumes:
      - ~/data/redis/rbac:/data
    ports:
      - 6379:6379
  rbac:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: rbac
    working_dir: /internal/rbac
    volumes:
      - ~/go/pkg/mod:/go/pkg/mod
      - ./internal:/internal
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    env_file:
      - .env
      - .secret.env
    depends_on:
      - postgresql
      - redis