CREATE TABLE IF NOT EXISTS "rbac_casbin_rules" (
    "id" TEXT PRIMARY KEY NOT NULL,
    "p_type" TEXT DEFAULT NULL,
    "v0" TEXT DEFAULT NULL,
    "v1" TEXT DEFAULT NULL,
    "v2" TEXT DEFAULT NULL,
    "v3" TEXT DEFAULT NULL,
    "v4" TEXT DEFAULT NULL,
    "v5" TEXT DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS v0v1v2v3 ON rbac_casbin_rules (v0, v1, v2, v3);