// Code generated by sqlc. DO NOT EDIT.

package rbacStore

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getInfoByIDTenantStmt, err = db.PrepareContext(ctx, getInfoByIDTenant); err != nil {
		return nil, fmt.Errorf("error preparing query GetInfoByIDTenant: %w", err)
	}
	if q.listBySignTenantStmt, err = db.PrepareContext(ctx, listBySignTenant); err != nil {
		return nil, fmt.Errorf("error preparing query ListBySignTenant: %w", err)
	}
	if q.totalBySignTenantStmt, err = db.PrepareContext(ctx, totalBySignTenant); err != nil {
		return nil, fmt.Errorf("error preparing query TotalBySignTenant: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getInfoByIDTenantStmt != nil {
		if cerr := q.getInfoByIDTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInfoByIDTenantStmt: %w", cerr)
		}
	}
	if q.listBySignTenantStmt != nil {
		if cerr := q.listBySignTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBySignTenantStmt: %w", cerr)
		}
	}
	if q.totalBySignTenantStmt != nil {
		if cerr := q.totalBySignTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing totalBySignTenantStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getInfoByIDTenantStmt *sql.Stmt
	listBySignTenantStmt  *sql.Stmt
	totalBySignTenantStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getInfoByIDTenantStmt: q.getInfoByIDTenantStmt,
		listBySignTenantStmt:  q.listBySignTenantStmt,
		totalBySignTenantStmt: q.totalBySignTenantStmt,
	}
}
