// Code generated by sqlc. DO NOT EDIT.

package rbacStore

import (
	"context"
)

type Querier interface {
	GetInfoByIDTenant(ctx context.Context, arg GetInfoByIDTenantParams) (RbacCasbinRule, error)
}

var _ Querier = (*Queries)(nil)
