// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/keepondream/RBAC_service/handle"
	"github.com/keepondream/RBAC_service/route"
	"github.com/keepondream/RBAC_service/server"
	"github.com/keepondream/RBAC_service/service"
	"github.com/keepondream/RBAC_service/store"
	"github.com/keepondream/RBAC_service/utils"
)

// Injectors from wire.go:

func InitRBACServer(configFile string) (*server.RBACServer, error) {
	config, err := utils.LoadConfig(configFile)
	if err != nil {
		return nil, err
	}
	db, err := server.NewDB(config)
	if err != nil {
		return nil, err
	}
	enforcer := server.NewEnforcer(config)
	logger := server.NewLogger(config)
	storeStore := store.NewStore(db)
	serviceService := service.NewService(config, enforcer, logger, storeStore)
	handleHandle := handle.NewHandle(config, enforcer, logger, storeStore, serviceService)
	engine := route.NewRoute(config, handleHandle)
	rbacServer := server.NewRBACServer(config, db, handleHandle, engine)
	return rbacServer, nil
}
